export const GET_CAPTCHA_REQUEST = 'GET_CAPTCHA_REQUEST';
export const GET_CAPTCHA_SUCCESS = 'GET_CAPTCHA_SUCCESS';
export const GET_CAPTCHA_ERROR = 'GET_CAPTCHA_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';
