export const POST_PHONE_REQUEST = 'POST_PHONE_REQUEST';
export const POST_PHONE_SUCCESS = 'POST_PHONE_SUCCESS';
export const POST_PHONE_ERROR = 'POST_PHONE_ERROR';

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_PHONE_ERROR';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
