export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';

export const POST_PHONE_REQUEST = 'POST_PHONE_REQUEST';
export const POST_PHONE_SUCCESS = 'POST_PHONE_SUCCESS';

export const USER_LOGOUT = 'USER_LOGOUT';
