export const GET_CHAPTER_REQUEST = 'GET_CHAPTER_REQUEST';
export const GET_CHAPTER_SUCCESS = 'GET_CHAPTER_SUCCESS';
export const GET_CHAPTER_ERROR = 'GET_CHAPTER_ERROR';

export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const GET_ALL_WEBINAR_REQUEST = 'GET_EVENT_REQUEST';
export const GET_ALL_WEBINAR_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_ALL_WEBINAR_ERROR = 'GET_EVENT_ERROR';

export const GET_EVENT_REQUEST = 'GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_ERROR = 'GET_EVENT_ERROR';
